export const DATETIME_FORMATS = [
  // this first format is the one generated by the datetime-local input type
  "yyyy-MM-dd'T'HH:mm",

  // this is more human-enterable in the case that we can't use the
  // datetime-local input type, it only applies to browsers that don't support
  // datetime-local
  "M/d/yyyy hh:mm a",

  // this format will assume the current date for you, it only applies to
  // browsers that don't support datetime-local
  "hh:mm a",
];
